### ISSUE TITLE
Introduction to tidyr/reshape2 package in R by Remi Daigle

### ISSUE THREAD

**Issue by ttimbers** [sciprog-sfu/sciprog-sfu.github.io#1]
**Where**: Simon Fraser University, Burnaby Campus, SSB 6178
**When**: 3:30 pm - 4:30 pm, Tuesday, July 14, 2015

**Dependencies**: R (http://cran.r-project.org/index.html), RStudio(http://www.rstudio.com/products/rstudio/download/), and the `tidyr` and `reshape2` packages.

note - packages can be installed by typing the following into the R console: 
`install.packages("tidyr")`
`install.packages("reshape2")`

**Data for this session can be downloaded by clicking here**: https://github.com/ttimbers/studyGroup/blob/gh-pages/lessons/2015-07-14/data/inflammation_data.zip?raw=true

**Public notepad for this session can be accessed here:**:
https://etherpad.mozilla.org/2015-07-14-SFU

**Lesson notes will be archived here**: http://remi-daigle.github.io/tidyr_reshape2_lesson/

**Comment by ghost** [comment]
Hi,
do you plan to record the event and broadcast it?

**Comment by ttimbers** [comment]
@marpello that is not the plan yet, but it is something we could discuss. Are you off campus or have a scheduling conflict? I think we could also post the lesson notes here on Github if that would also be helpful.

**Comment by NickDulvy** [comment]
Hi: Is there any chance you would be willing to commit to running this at a later date, say three months out so we can take best advantage of your skills? Also are you on the statzbeers mailing list/ twitterfeed?
http://www.dulvy.com/statz-beerz.html
Cheers,

**Comment by remi-daigle** [comment]
Hey @NickDulvy,
Unfortunately, I can't commit to running this particular lesson in ~3 months since I'm moving back East at the end of August. However, I am following the statzbeers mailing list/ twitterfeed and I posted the lesson [here](http://remi-daigle.github.io/tidyr_reshape2_lesson/). We're also planning to record a screencast of the lesson.
