### ISSUE TITLE
"Building Shiny apps for interactive data analysis" by Dean Attali

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#101]
## Description

Shiny is a package that lets you transform your R code into an interactive web page. With shiny you can share your R code or analysis with people who don't know R, or you can use it to make your analysis interactive and easy by exposing it using a graphical user interface instead of through programming. In this tutorial you'll learn what shiny is, see examples of shiny apps, learn how to create shiny apps, and get an introduction to some of the key concepts in shiny programming.
## Time and Place

**Where:** Simon Fraser University, Burnaby Campus, Library Research Commons
**When:** Monday, August 15th, 10:30-12:30 am

⟶ **Note that this is a two-hour workshop!**
## Registration

[**REGISTER HERE**](http://www.lib.sfu.ca/node/30630/sfu_register)
### Software Dependencies
- `R` (≥ 3.0.0)
- `shiny` package 
## Links

**Etherpad:** TBA
**Lessons Notes:** http://deanattali.com/blog/building-shiny-apps-tutorial/
## Attending SciProg Organizers
- @brunogrande
- @razoumov 
- @theavanrossum

**Comment by BrunoGrandePhD** [comment]
@daattali, when you get a chance, comment with the details relating to your workshop so I can update the "TBA" values. Also, feel free to give me an updated title for the workshop.

**Comment by BrunoGrandePhD** [comment]
@daattali, in order to create a registration page and properly advertise your workshop, we'll need more details. Please respond by this coming Monday with a description of what you plan on instructing and any prerequisites needed by attendees (_e.g._ which minimum version of R, any required packages).

**Comment by daattali** [comment]
Sorry  Bruno I'm away for a couple weeks at conferences and haven't thought
about this at all. I'll try to reply within a day

---

http://deanattali.com

**Comment by BrunoGrandePhD** [comment]
@daattali, no worries. I look forward to your response!

**Comment by daattali** [comment]
Title: Building Shiny apps for interactive data analysis
Description: Shiny is a papckage that lets you transform your R code into
an interactive web page.  With shiny you can share your R code or analysis
with people who don't know R, or you can use it to make your analysis
interactive and easy by exposing it using a graphical user interface
instead of through programming. In this tutorial you'll learn what shiny
is, see examples of shiny apps, learn how to create shiny apps, and get an
introuction to some of th ekey concepts in shiny programming.
Prereqs: install the "shiny" package (it's on CRAN, should be easy to
install without any problems), any R version will do as long as it's new
enough that shiny gets installed
Links: I don't think I'll be using etherpad and I'm not sure what the
registration link is supposed to be? For lecture notes you can put
http://deanattali.com/blog/building-shiny-apps-tutorial/

Sorry the description isn't great and is so late, useR conf schedule is
super packed!

---

http://deanattali.com

**Comment by BrunoGrandePhD** [comment]
I wish I could be there! Based on Twitter alone, it looks like an awesome conference!

**Comment by BrunoGrandePhD** [comment]
@daattali, thanks for the description! This works fine.

**Comment by razoumov** [comment]
May I make a suggestion? I'd like to see how to visualize a 3D Cartesian volume in Shiny, showing one 2D cross-section at a time (Shiny should be able to do this?), and using a slider to cycle through all cross-sections. Thanks!

**Comment by daattali** [comment]
@razoumov I'm sorry but that sounds like an extremely specific question that isn't going to be applicable to most people. It's also not a simple thing to do, Shiny doesn't support that kind of visualization natively (it can be done but you'd have to know javascript)

**Comment by daattali** [comment]
Does anyone know if there's free parking at SFU? I'm going to be driving from UBC because I don't want to bus that early, but I'm also hoping not to pay a fortune for parking :)

**Comment by lpix** [comment]
No free parking. You can park down the hill on Hastings and Duthie, and take the 135 or 144 from there. Or do the same on Production Way, and take the 145. 
I recommend Hastings, there's a better chance of catching a bus there.

**Comment by BrunoGrandePhD** [comment]
## Workshop Format

@daattali, I'm sure you'll give a great workshop. I still thought that I should share [some guidelines](https://github.com/sciprog-sfu/sciprog-sfu.github.io/blob/master/lessons/README.md) we wrote up a few weeks ago. You just need to read the "During the Workshop" section. If you've been to a Software Carpentry workshop, you'll know about the sticky notes. If not, there's more information earlier in the document about using them. Let me know if you have any questions. 

## Driving Directions

A colleague of mine usually parks on Sperling near Hastings. Apparently, there's free parking there (no time limit). He then buses up the mountain on the 135 bus, as @lpix suggested. 
1. Drive to Sperling near Hastings. You should be able to find free parking. 
2. Walk up to Hastings and take the 135 bus up the mountain. See [Google Maps](https://goo.gl/maps/YtdYiBNU1Tk). 
3. Use the walking directions posted below to get to the appropriate room. 

<img width="1136" alt="walk_to_library" src="https://cloud.githubusercontent.com/assets/740725/17644792/bad59064-6145-11e6-87c3-c4935cd21754.png">

**Comment by daattali** [comment]
Thanks Bruno

Can someone show up 10 min early to open the door for me?

I didn't plan on bringing any sticky notes, do you guys have from other
sessions?

**Comment by BrunoGrandePhD** [comment]
I'll be there early to make sure you can get in. And I think I have some leftover sticky notes from other workshops. I'll bring them if I can find them.

**Comment by daattali** [comment]
Do you guys know if there is free guest wifi on campus?

**Comment by BrunoGrandePhD** [comment]
We have eduroam, if you have access to that. Otherwise, I can login using my SFU credentials.

**Comment by daattali** [comment]
My eduroam doesn't work anymore, I might need you to use your credentials .. :)
