### ISSUE TITLE
Hacky Hour for June 2016

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#102]
We should organize a hacky hour every month or so. This is for organizing the June 2016 SciProg Hacky Hour. Can the organizers comment with which day of the week they're on campus and available to go to Club Ilia in the evening (and indicate any exceptions in June)? Afterwards, we'll send out a Doodle poll to SciProg to settle on a week. I'm open to suggestions!

**Edit**

It'll be on June 30th at Club Ilia!

**Comment by vguerracanedo** [comment]
I'm available after 4pm before the 21st

**Comment by lpix** [comment]
Wednesdays and Thursdays usually work for me (also after 4pm)

**Comment by BrunoGrandePhD** [comment]
Pinging @theavanrossum.

**Comment by theavanrossum** [comment]
Unfortunately I'm busy until June 28th - except for the 21st . @vguerracanedo I assume that was an exclusive "before"? I'm free 28/29/30

**Comment by vguerracanedo** [comment]
It was, but then my plans for the 21st went down the drain. I'm down to chill on the 21st.

**Comment by BrunoGrandePhD** [comment]
Unfortunately, my lab social, which was supposed to happen this past Tuesday, was postponed to this coming Tuesday, June 21st. Funnily enough, we were planning on holding it at Club Ilia, where we would likely hold this Hacky Hour. 

@vguerracanedo, are you now available only on the 21st? Or also for the rest of the month?

**Comment by vguerracanedo** [comment]
I'm free until mid July. I thought I was going to join a workshop on the week of the 21st, but I'm not anymore.

**Comment by BrunoGrandePhD** [comment]
In that case, let's hold the Hacky Hour at the end of June. 

@lpix, among June 28/29/30, which days are you available in the evening?

**Comment by lpix** [comment]
The 29th and 30th look good for me!

**Comment by BrunoGrandePhD** [comment]
For me, June 30th works best. Let's go with 6:00 pm.
