### ISSUE TITLE
[Cancelled] "Machine Learning and Random Forest" by Jason Barker

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#107]
## Description

**This workshop has been cancelled.**

We will explore the pros and cons of using random forests for regression and classification,
using examples from [UCLA's Machine Learning Repository](http://archive.ics.uci.edu/ml/) and the R classic, Iris. 
## Time and Place

**Where:** Simon Fraser University, Burnaby Campus, Library Research Commons
**When:** Monday, August 22nd, 10:30-11:30 am
## Registration

Cancelled.
## Required Preparation

**Software Dependencies** 
- `R` (version ≥ 3.1)
- `randomForest` package
- `ggplot2`
## Links

**Etherpad:** TBA
**Lessons Notes:** TBA
## Attending SciProg Organizers
- @brunogrande
- @razoumov 
- @lpix

**Comment by BrunoGrandePhD** [comment]
@Hypogeous, when you get a chance, comment with the details relating to your workshop so I can update the "TBA" values. Also, feel free to give me an updated title for the workshop.

**Comment by BrunoGrandePhD** [comment]
@Hypogeous, in order to create a registration page and properly advertise your workshop, we'll need more details. Please respond by this coming Monday with a description of what you plan on instructing and any prerequisites needed by attendees (_e.g._ which minimum version of R, any required packages).

**Comment by Hypogeous** [comment]
Hello. I have attached my brief description of the workshop. Let me know if you
think more detail is in order. 
[Barker_Random.txt](https://github.com/sciprog-sfu/sciprog-sfu.github.io/files/335984/Barker_Random.txt)

**Comment by BrunoGrandePhD** [comment]
@Hypogeous, thanks!
