### ISSUE TITLE
SciProg Hackathon - Idea

### ISSUE THREAD

**Issue by lpix** [sciprog-sfu/sciprog-sfu.github.io#110]
I think this would be a great way to engage with our members, socialize, learn, and all that good stuff.

In a normal hackathon, each team comes up with a problem to investigate and work on for the duration of the event (usually a week). There are also other events and talks that participants would go to. 

_I have never been to a hackathon, but always wanted to participate in one, so I'm trying to convince @brunogrande that we should make one -- maybe as an End of Summer/Beginning of Fall Special event?_

Since the (first-ever) Genomics Hackathon in Vancouver is taking place in October and  @brunogrande and @ttimbers are already busy organizing it, we can hold off on organizing something that big.
But, we can have a mini-hackathon:
- We could use a not-so-Google-searchable problem for participants to work on (like identify the protein sequence in sea stars that...) 
- Then we could ask them to create a mock app to publish and share their results.

**_The key is to simulate the real-world process from research to contributing and sharing knowledge_**

Any ideas?

**Comment by vguerracanedo** [comment]
This sounds like a good idea to me. I'll be away for part of July and August, so I would be of little help organizing the event. Let me know if I can be of any help remotely.

**Comment by lpix** [comment]
So far it's just an idea, I'm hoping more organizers will like it so that we can put it into practice in the future.
