### ISSUE TITLE
Summer advertising push

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#113]
Here's the list of people/departments we want to target for advertising. 
## Departments
- [ ] Biological Sciences / @vguerracanedo
- [ ] Biomedical Physiology & Kinesiology
- [ ] Chemistry
- [ ] Computer Science / @lpix 
- [ ] Earth Sciences
- [ ] Mathematics
- [x] Molecular Biology and Biochemistry / @brunogrande
- [ ] Physics
- [ ] Statistics and Actuarial Science
- [ ] School of Engineering Science
## Professional Development
- [x] Dean of Graduate Studies (via Gladys' monthly email updates) / @brunogrande
- [ ] Library/Research Commons / @vguerracanedo
- [ ] APEX Program / @vguerracanedo
## Student Groups and Unions
- [x] Stats Beerz / @brunogrande
- [x] MBB Student Union / @brunogrande
- [ ] Computer Science Student Union
- [x] SFU Satellite Club / @lpix 
- [ ] Robotics Club / @lpix 
## Classes

Pick a set of classes based on the department. See https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/95 for information on the classes and the professors. 
- [x] Computing Science (9 courses) / @lpix 
- [ ] Molecular Biology and Biochemistry (4 courses) / @lpix 
- [ ] Statistics (2 courses)
- [ ] Physics (3 courses)
- [x] Engineering Science (2 courses) / @lpix
- [ ] Chemistry (2 courses)
- [x] Health Sciences (3 courses) / @lpix

**Comment by BrunoGrandePhD** [comment]
Can each of the @sciprog-sfu/organizers edit my issue above and pick three people/departments to target? Thanks!

**Comment by BrunoGrandePhD** [comment]
Wait until I post the advertising slide/image here before advertising.

**Comment by lpix** [comment]
I also suggest splitting the list from #95 since I've listed 20 professors in 7 departments. 

So, I'll take Computer Science, SFU Satellite Club, Robotics Club, and the CompSci classes in the list.

_Question: How do you edit the issue?_ :confused:

**Comment by BrunoGrandePhD** [comment]
@lpix I hadn't added you as an admin of the sciprog-sfu GitHub organization. You can click the pencil icon at the top-right of the issue.

**Comment by BrunoGrandePhD** [comment]
I created a slide for promoting SciProg. I circulated it via email and waiting for feedback. I will post the final version here on Monday.

**Comment by lpix** [comment]
thanks @brunogrande! If there are profs/departments yet to be assigned, I can contact them as well...I'll check back on Monday

**Comment by BrunoGrandePhD** [comment]
I've been using my slide as an inline image in the emails I've been sending. 

<img width="720" alt="sciprog_promo_large" src="https://cloud.githubusercontent.com/assets/740725/16510856/a9bb29b0-3efe-11e6-9a77-3bfc0bf138a3.png">

**Comment by MaralDehghani** [comment]
I believe you have too add the School of Engineering Science to the target list.

**Comment by BrunoGrandePhD** [comment]
@MaralDehghani Thanks for letting us know! I've added it here and updated [our growing list of targets](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/109). Do you want to email Engineering Science? This is the email template I've been using. Short and sweet. 

> If you're programming as part of your research (or want/need to), I invite you to join the SciProg study group community! We organize one-hour skill-sharing workshops and Q&A sessions every week as well as hacky hour socials every month. You can find our summer schedule on the slide below and on [our website](http://sciprog.ca/). 
> 
> **⟶ If you're interested in joining the SciProg study group, you can fill [this form](http://goo.gl/forms/OXNe5kB8ao) and you'll be added to the mailing list.**
> 
> Feel free to forward this information to your friends! 
> 
> <img width="720" alt="sciprog_promo_large" src="https://cloud.githubusercontent.com/assets/740725/16510856/a9bb29b0-3efe-11e6-9a77-3bfc0bf138a3.png">

**Comment by MaralDehghani** [comment]
Hi Bruno. Sure. I will send an email to ENSC, and thanks for the template.
I probably send it next week, cause I do not want to add an unread message to the long weekend pile of emails!
