### ISSUE TITLE
Using Galaxy for Data Analysis by Bruno Grande

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#12]
[Galaxy](https://galaxyproject.org/) provides a user-friendly interface for running complex computational tasks and pipelines. For people just starting out, this provides an easy means to perform data analysis. That is, until they learn more about the shell, etc.

**Comment by aliojjati** [comment]
Can you elaborate ?

**Comment by BrunoGrandePhD** [comment]
I added some more details to this issue.
