### ISSUE TITLE
Creating e-mail banner templates

### ISSUE THREAD

**Issue by lpix** [sciprog-sfu/sciprog-sfu.github.io#122]
The images for Facebook are too big for e-mail.

**Comment by lpix** [comment]
@vguerracanedo are you ok filling out these templates ? or we can both do one every other week, what do you think?

**Comment by vguerracanedo** [comment]
Hi Leslie, 
Could you tell me a little more about the e-mail banners? Would we have to create an individual e-mail banner for each session? 
V

**Comment by lpix** [comment]
I'll make templates like the ones I made for Facebook. You'll just need to fill in the details and save as a new image. I was hoping to finish them before this Monday, but I don't see that happening :(
