### ISSUE TITLE
Software Carpentry - Sessions

### ISSUE THREAD

**Issue by lpix** [sciprog-sfu/sciprog-sfu.github.io#123]
This issue is for planning the Software Carpentry sessions.

Dates: 
R Session: September 20 & 21 
Python Session: September 22 & 23 

Times: TBD

**Comment by theavanrossum** [comment]
Yes to more SCWs! I'll be away for these dates but also for a lot of time between now and mid-October, so it may not be feasible to schedule around me.

**Comment by SimonGoring** [comment]
I'd be happy to volunteer during the R sessions.   I have kid duties in the mornings & afternoon but can be there for some of the time if that helps.

**Comment by razoumov** [comment]
FYI, there are two confirmed SWC workshops at SFU's Research Commons:
- R on October 3-4 (main contact Alex)
- Python on Oct 5-6 (main contact Bruno)

**Comment by lpix** [comment]
@theavanrossum :  that's too bad! We are still figuring out dates and times, maybe you can volunteer for part of a session.
@razoumov : I was under the impression they were in September... I'll change the calendar. You and @brunogrande can always edit this issue with whatever else you might need so that other admins can help you organize the event.
@SimonGoring: Thanks for your interest! We are still figuring out some details but we will have more info on dates and times by the beginning of next semester.

**Comment by BrunoGrandePhD** [comment]
@lpix: The suggested dates in September were merely tentative. In a private email, Nicole informed Alex and I that October would work best for booking rooms. 

We will post links to the workshops' registration pages once they're created. Subscribe to this issue (button at the bottom right) if you wish to stay up-to-date.

**Comment by razoumov** [comment]
Here is the R workshop page https://computecanada.github.io/2016-10-03-sfu .

**Comment by BrunoGrandePhD** [comment]
And here is the Python workshop page: http://bgran.de/2016-10-05-SFU/
