### ISSUE TITLE
SciProg presence at Graduate Student Orientation

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#125]
This was brought up at the recent meeting with the Research Commons librarians. They offered to plug SciProg, because they will have a kiosk. But I was thinking whether we should host our own kiosk there. Thoughts?

Link: https://www.sfu.ca/dean-gradstudies/events/orientation.html

**Comment by vguerracanedo** [comment]
This sounds like a good idea. I may be away on the 2nd, but I can help with the logistics.

**Comment by lpix** [comment]
Great idea! do we need to consider a budget for this? I am thinking business cards, posters, or pens...not to mention handing out a semester schedule, at least

**Comment by BrunoGrandePhD** [comment]
I talked with Nicole and she offered that we attend their kiosk over lunch. This seems like the simplest solution. I agree with @lpix that we should bring some material. I think a simple flyer with information about our Fall workshops and how to sign up for the mailing list can suffice. 

@lpix, do you want to create that flyer after your exams are over? You've been creating great promo material for the workshops. 

@vguerracanedo, I'll be sure to let you know if I need any help.

**Comment by BrunoGrandePhD** [comment]
@lpix: If you accept to create the flyer once you have the time, can you create a new GitHub issue for it? Thanks!
