### ISSUE TITLE
Promotion Material Fall 2016

### ISSUE THREAD

**Issue by lpix** [sciprog-sfu/sciprog-sfu.github.io#130]
This fall looks like it's going to go pretty well! I'll be making the visual promotional material for the Grad Orientation and start on the confirmed workshops. Any ideas are welcome in the comments.
- [ ] Graduate Orientation kiosk
- [ ] Facebook / E-Newsletter
- [ ] Hacky Hour

**Comment by lpix** [comment]
#126

**Comment by vguerracanedo** [comment]
Thank you for being so on it! I don't have any ideas on the top of my mind, but I would be down to meet for an hour to help create some of the materials.

**Comment by lpix** [comment]
Sure! I'll be there next Monday, we can meet after that

**Comment by vguerracanedo** [comment]
Cool
