### ISSUE TITLE
Machine learning in Python

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#133]
This workshop would cover machine learning in Python using scikit-learn. Depending on how much time is needed, it can cover just one topic (random forest) or multiple topics to highlight scikit-learn's flexibility.

**Comment by eadeeb** [comment]
That sounds fascinating, I would attend this and could find others who would as well.

**Comment by BrunoGrandePhD** [comment]
This will be happening on December 6th (see #147).
