### ISSUE TITLE
Intro to Database Design by Dan Fornika

### ISSUE THREAD

**Issue by dfornika** [sciprog-sfu/sciprog-sfu.github.io#135]
## Description

Relational databases allow us to store large amounts of data in a well-organized structure. This allows us to query and analyze our data using a 'Structured Query Language' (SQL). But a well-organized database doesn't happen automatically. How can we take our scientific data and prepare it for storage in a database? How can we ensure that our stored data is valid and consistent?
## Time and Place

**Where:** Room 7010, Library Research Commons, SFU Burnaby Campus

**When:** 15:00 on Tuesday, November 22nd 2016
## Registration

TBD
## Required Preparation

TBD
### Assumed Knowledge

TBD
### Software Dependencies

TBD (Will probably use SQLite because it's a lightweight install compared to MySQL or PostgreSQL).
#### Mac OS X

TBD
#### Windows

TBD
#### Linux

TBD
### Data

TBD
## Links

**Lessons Notes:** (Link to lesson notes. Let the admins know if you need help to post this.)

**Etherpad:** (Optional, but useful for sharing code with learners. Use URL 
like: https://etherpad.wikimedia.org/p/2016-11-22-database)
## On-site SciProg Organizers

TBD

**Comment by dfornika** [comment]
I did a LaTeX workshop instead of this. I think other(s) have proposed the same idea so I'm going to close this issue.

**Comment by BrunoGrandePhD** [comment]
Sounds good!
