### ISSUE TITLE
How to Lead a Study Group Session

### ISSUE THREAD

**Issue by ttimbers** [sciprog-sfu/sciprog-sfu.github.io#14]
- Plan a lesson on your topic for a one hour time slot
- Ensure the topic is of general interest
- Please do not use lecture slides, but present the material using a live coding demonstration approach
- Plan 2-3 challenge questions to give to your learners
- Use two-different colored post-it notes (these will be provided) to communicate with your learners, use one color to signify "slow down" and one color to signify everything is "A-OK!"
- Please share your lesson plan/outline with us via a link, pull request or email

**Comment by BrunoGrandePhD** [comment]
Maybe we can store this as a Markdown file in the actual repository, so we can edit it over time and track it using version control. I prefer that than either editing your issue or creating a long unorganized list of comments on this issue. 

What do you think?

**Comment by ttimbers** [comment]
Sounds good to me!

**Comment by katieannemills** [comment]
Note [this directory](https://github.com/ttimbers/studyGroup/tree/gh-pages/lessons) is a good place to house all your lesson notes, or links to them (like for example, [this lesson](https://github.com/minisciencegirl/studyGroup/blob/gh-pages/lessons/ggplot2/lesson.md) is just a pointer to the independent lesson repo).

**Comment by aliojjati** [comment]
One thing we all have noticed is that there are tons of educational material out there. 

The question is what is it that makes the material here most useful ? I think it would be most relevant if it addresses (answers)  the specific tasks (questions) participants are concerned about. So, maybe it would be good to have a survey from the participants about how they are going to implement what they learn into their work. It could help design the examples based on that ...

**Comment by BrunoGrandePhD** [comment]
I've created a [Markdown document](https://github.com/ttimbers/studyGroup/tree/gh-pages/lessons) in the repo to track the guidelines for leading a study group session. If you're okay with it, I'll change the link on the website to the Markdown document.
