### ISSUE TITLE
"Intro to LaTeX" by Dan Fornika

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#140]
## Description

Introduction to the LaTeX typesetting system, using the online editor 'ShareLaTeX'.
## Time and Place

**Where:** Room 7010, Library Research Commons, SFU Burnaby Campus

**When:** Tuesday, November 22nd, 2016 at 3:00 pm
## Registration
http://www.lib.sfu.ca/about/branches-depts/rc/31734

### Assumed Knowledge
This will be a beginner-friendly workshop to introduce the basics of LaTeX. Some LaTeX syntax for formatting mathematical equations will be introduced, but no technical knowledge is assumed aside from basic web browsing and word processing.

### Software Dependencies
A modern web browser (Google Chrome or Firefox). We'll use the online LaTeX editor [ShareLaTeX](https://www.sharelatex.com/)

## Links

**Lessons Notes:**
https://github.com/dfornika/2016-11-22-intro-to-latex

**Etherpad:**
https://etherpad.wikimedia.org/p/2016-11-22-intro-to-latex

**Comment by BrunoGrandePhD** [comment]
@dfornika: Are you able to update the description of the issue above? I'm not sure how the permissions work out.

**Comment by dfornika** [comment]
Yes, looks like I'm able to edit it.

**Comment by Faezehbeigi** [comment]
Hi Dan,

How can I have your email? I will definitely come to this workshop but I was wondering if it is possible to ask you question earlier.

Thanks,
Faezeh

**Comment by dfornika** [comment]
@Faezehbeigi you can reach me at dfornika@gmail.com
