### ISSUE TITLE
Machine Learning in Python by Jordan Lui and Lee Sutton

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#147]
## Description

In this introductory look at Machine Learning you will learn about the different types of Machine Learning models and build your first regression model. You'll learn about some of the considerations to fine-tune your model and improve convergence. We'll also show you some great online resources to learn about new ML models and get great example code for your own projects.

This workshop is intended for users who are new to Machine Learning. Users should already have installed Python 2 or Python 3 before this session.

## Time and Place

**Where:** Room 7200, Library Research Commons, SFU Burnaby Campus

**IMPORTANT:** In room 7200, not 7010.

**When:** 2016-Dec-06, 3pm
## Registration
http://www.lib.sfu.ca/about/branches-depts/rc/31706

### Assumed Knowledge

(You can’t cover much in 1-2 hours, so it’s better that you expect some 
prerequisite knowledge. For example, if you’re going to teach about an R 
package, it’s recommended that you assume familiarity with the R language.)
### Software Dependencies

(If there is one page you can link to for all operating systems, feel free 
to delete the following sections and post the link.)
#### Mac OS X

(Mac OS X installation instructions)
#### Windows

(Windows installation instructions)
#### Linux

(Linux installation instructions)
### Data

(Links to data files used in your workshop. Let the admins know if you need 
help to post the files online.)
## Links

**Lessons Notes:** (Link to lesson notes. Let the admins know if you need help to post this.)

**Etherpad:** (Optional, but useful for sharing code with learners. Use URL 
like: https://etherpad.wikimedia.org/p/2016-06-13-nameOfLesson)
## On-site SciProg Organizers

*

**Comment by jordanlui** [comment]
So excited for this!! :)
