### ISSUE TITLE
"Useful tools in my ~/.bashrc file" by Alex Razoumov

### ISSUE THREAD

**Issue by razoumov** [sciprog-sfu/sciprog-sfu.github.io#151]
## Description

Over the years I have accumulated lots of useful bash scripts, from replacing some of the default Linux commands to data manipulation to very efficient archival/restore tools. All of these are always preloaded via my ~/.bashrc file. I'll go through some of these tools in this workshop.

## Time and Place

**Where:** Room 7010, Library Research Commons, SFU Burnaby Campus

**When:** January 24th, 2017 @ 3:00 PM

## Registration

TBA

### Assumed Knowledge

Basic knowledge of Bash.

### Software Dependencies

You need Bash to be installed on your computer (either your laptop or a remote server). Look into [Git Bash](https://git-for-windows.github.io/) for Windows. Bash should already be installed on Macs and Linux machines.

Another tool I'll use a lot in the presentation is DAR (http://dar.linux.free.fr), an open-source replacement for the tar command. In Linux and MacOS DAR can be installed via your favourite package manager, or compiled from source. It's also been tested in Windows, although I don't have the details.

## Links

All definitions and scripts can be found in "bashrc" file inside https://github.com/razoumov/bashrc.git .

**Comment by BrunoGrandePhD** [comment]
@razoumov: I like this idea a lot. Would you be available to teach it on January 24th at 3:00 PM?

**Comment by razoumov** [comment]
@brunogrande Sure, I'll be happy to. Put me in for Jan-24.

**Comment by BrunoGrandePhD** [comment]
Great! I added more details to your original issue. Feel free to edit as you see fit.
