### ISSUE TITLE
"Version control and collaborating with Git and Github: To save your future self from stress!" by Jessica Walsh

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#173]
## Description  

Learn the benefits of using Git to track your changes, improve workflow and share code in collaborative projects. This will be designed for beginners, as we will go over the basics of Git and Github. Basic knowledge of Bash and R Studio will be helpful.

**Git can be used to prevent this from happening!**

<img src="https://user-images.githubusercontent.com/740725/33356232-594896ea-d4f6-11e7-9b6f-81f93a8c5a6e.gif" width="500" alt="Git can be used to prevent this from happening!" />

## Time and Place

**Where:** !!! IMPORTANT !!! Workshop in different room than usual.  Room 3008, W.A.C. Bennett Library, SFU Burnaby Campus 

**When:** Tuesday, December 5th, 2017 at 3:00-4:30 PM

### Assumed Knowledge

Basic use of Bash Shell if preferred, but not necessary. 
Basic use of R and RStudio, and understanding of RStudio Projects is preferable.

### Software Dependencies

1. Download Bash Sell, Git, a Text Editor, R and R studio.

    These user friendly instructions from Software Carpentry show how to download these programs. https://swcarpentry.github.io/workshop-template/#setup

    If you have any problems, please consult this Wiki help page: https://github.com/swcarpentry/workshop-template/wiki/Configuration-Problems-and-Solutions

2. Signup for a GitHub account

    Create a new GitHub account if you don't already have one: https://github.com/. Click on green button, select the free account, and confirm your account via the link sent to your email. 

    If you want to keep your code private to share with collaborators online, ask for a discount for academics: https://education.github.com/discount_requests/new

**Comment by gallingerj** [comment]
In case it's of interest, here are some good pre-existing instructional materials that could be recycled: 
https://github.com/mozillascience/friendly-github
https://swcarpentry.github.io/git-novice/

The friendly GH slides are in [issue 10](https://github.com/mozillascience/friendly-github/issues/10).

**Comment by jsdodge** [comment]
Is it important to use the latest version of git? I am running OS X 10.11.6, and have git version 2.10.1 (Apple Git-78). I tried to install git-2.15.0-intel-universal-mavericks and but the disk image would not open. It looks like I'm not alone: https://github.com/timcharper/git_osx_installer/issues/100.

**Comment by BrunoGrandePhD** [comment]
@jsdodge: The instructor, @jessicawalsh1, can have the final word, but I don't think having the absolute latest version is necessary. Anything relatively recent should be fine. Version  2.10.1 was release in October 2016, which is recent.

**Comment by jessicawalsh1** [comment]
@jsdodge Thanks for the question. Sorry for the troubles. It seems there is a problem with the next version. The version you have should be fine, as we will be doing pretty simple stuff. You might get issues with git talking to RStudio - have you tried that? Based on the discussion of the error you sent, it seems like version 2.14 works.
