### ISSUE TITLE
"Getting started with emacs" by Marie-Helene Burle

### ISSUE THREAD

**Issue by prosoitos** [sciprog-sfu/sciprog-sfu.github.io#178]
## Location, date and time

Room 7010, Library Research Commons, SFU Burnaby Campus
October 24, 2017
3–4:30 pm

## Description

All information about the workshop, including pre-requisites at:
https://github.com/prosoitos/workshop_getting-started-with-emacs

**Comment by BrunoGrandePhD** [comment]
@prosoitos: I already created an issue for your workshop here based on your previous workshop, as you asked: https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/174. I've already linked to it in different places, so it's best that we edit that one. Let me know if you want to make any changes. I've updated the links to your new workshop repository.
