### ISSUE TITLE
"Introduction to Database and SQL" by Fatemeh Salehian Kia

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#180]
## Description

This is an introductory course on Databases and SQL Querying. There are no pre-requisites for this workshop. If you are looking to get acquainted with the concept of Databases and Queries, this is the right workshop for you.
 
**Requirements:**
Bring your laptop and we will walk through very basic installation to setting up your environment to creating your first table and writing queries against it.

## Time and Place

**Where:** Room 7010, Library Research Commons, SFU Burnaby Campus

**When:** Thursday, March 22nd, 2018 at 3:30 PM

## Registration

[**REGISTER HERE**](https://www.lib.sfu.ca/about/branches-depts/rc/services/workshops/33129)

**Comment by caspgin** [comment]
Hi
I was instructed to install xampp which I did but the setup crashed while running and then it showed the software is installed. How do I check if it is completely installed or not?

**Comment by BrunoGrandePhD** [comment]
@caspgin: Depending on your OS, you should now have access to the `mysql` command line program in your preferred shell program.

**Comment by gwleung** [comment]
I recently took this workshop with Fatemeh and and looking for more individual help with Sql. Is there an email I can contact to get more help? Thanks!
