### ISSUE TITLE
"Scientific visualization with Plotly" by Alex Razoumov

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#183]
## Lesson notes

At https://github.com/razoumov/publish/blob/master/plotly.md.

## Description

In this one-hour workshop we will take a look at using Plot.ly open-source Python library for scientific visualization. We will start with simple 2D plots, create some interactive geographical maps, and then will move to more advanced 3D plotting and animations in a web browser.

## Requirements

You will need Python 3 installed on your laptop, along with the 'pip' package manager. In addition, please install Plot.ly Python library with

```
$ pip install plotly
```

If you want to store plots online (as opposed to storing them as offline html5 files or displaying them inside a Jupyter notebook), please sign up for a [free Plot.ly account](https://plot.ly/accounts/login/?action=signup). I will demonstrate switching between online and offline plotting.

If you want to plot inside Jupyter notebooks, please make sure you have Jupyter installed inside the Python environment on your laptop. You don't have to use Jupyter in this workshop, however, if you prefer running standalone Python scripts.

No prior plotting or Python experience is required to attend this workshop.

## Time and Place

**Where:** Room 7010, Library Research Commons, SFU Burnaby Campus

**When:** Tuesday, April 10th, 2018 at 3:30 PM

## Registration

[**REGISTER HERE**](https://www.lib.sfu.ca/about/branches-depts/rc/services/workshops/33221)

**Comment by razoumov** [comment]
Do we know the number of registrants so far for this workshop?
