### ISSUE TITLE
"Handling multiple large files the easy way using Python" by Laura Gutierrez Funderburk

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#184]
## Description

This workshop will cover tools and tricks on Python that make navigating large data files easier. Tools include comprehension lists, tables and dictionaries. The tools shared throughout this workshop can make tasks more efficient, particularly when manipulating data from multiple large files and file types. 

## Requirements

This workshop assumes knowledge and comfort using for, while and if statements. It also assumes enough comfort with the Python environment such as importing libraries and calling functions within them. Pre-installed software includes Python (I recommend installing either Anaconda or Miniconda to make this process easier), Excel and a text editor (such as notepad, gedit, notepad++, TextWrangler). Knowledge of Jupyter Notebooks is a plus, but if interested participants do not posses it, we can dedicate the first part of the workshop to getting comfortable with it.

## Time and Place

**Where:** Room 7200, Library Research Commons, SFU Burnaby Campus

**When:** Tuesday, April 24th, 2018 at 3:30 PM

## Registration

[**REGISTER HERE**](https://www.lib.sfu.ca/about/branches-depts/rc/services/workshops/33222)

## Lesson

https://lfunderburk.github.io/Handling-multiple-large-files-the-easy-way-using-Python/

**Comment by lfunderburk** [comment]
Completed
