### ISSUE TITLE
"Presenting Arch Linux" by Marie-Hélène Burle

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#185]
## Description

Is your Operating System Windows, macOS, or a prepackaged linux distribution running "out-of-the box" like Ubuntu and are you curious to hear about Arch Linux?

I will introduce this linux distribution which "focuses on elegance, code correctness, minimalism and simplicity, and expects the user to be willing to make some effort to understand the system's operation" ([source](https://en.wikipedia.org/wiki/Arch_Linux)). It relies on the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) ("keep it simple, stupid"): no bloatware, nothing installed that you might not want, no hidden complexity. Arch has a beautiful [Wiki](https://wiki.archlinux.org/), so well done that it serves as a reference for many on other linux distributions, and a very helpful community. Obviously, the necessary consequence of its philosophy is that it requires some investment as you will have to set and install everything you need.

If you have always been curious—or maybe even tempted—to make a big jump and go linux, this workshop is for you!

I will present the basic functioning of this OS and some of the tools that can make a workflow on linux really fun.

## Requirements

The workshop is open to all and those interested in playing with Arch are welcome to install it using VirtualBox. This is not necessary and you are welcome to just sit and watch.

## Time and Place

**Where:** Room 7010, Library Research Commons, SFU Burnaby Campus

**When:** Tuesday, April 3rd, 2018 at 3:30 PM

## Registration

[**REGISTER HERE**](https://www.lib.sfu.ca/about/branches-depts/rc/services/workshops/33220)

**Comment by prosoitos** [comment]
Link to the workshop [here](https://github.com/prosoitos/workshop_arch-linux).

**Comment by prosoitos** [comment]
Just noticed the start at 3:30 pm instead of the regular 3 pm. And other workshops are also starting at 3:30 pm. Is that a mistake or was it to accommodate someone?? Is 3:30 pm the new official time?

**Comment by BrunoGrandePhD** [comment]
I had gotten a few requests from instructors for 3:30 PM, so most workshops this semester were set to 3:30 PM. It wasn't meant as a permanent change. If SciProg continues during the summer, it can be returned to 3:00 PM.
