### ISSUE TITLE
"A taste of parallel programming with Chapel" by Alex Razoumov

### ISSUE THREAD

**Issue by lfunderburk** [sciprog-sfu/sciprog-sfu.github.io#191]
## Description

Chapel is a relatively new high-level programming language for shared- and distributed-memory machines. It combines the ease-of-use of Python and the speed of C++ and is the perfect language to learn the basics of parallel programming, whether you are trying to accelerate your computation on a multi-core laptop or on an HPC cluster. In this one-hour hands-on introduction I will go over several of Chapel's high-level abstractions.

## Requirements

All attendees will need to bring their laptops with a remote ssh client installed (on Windows I recommend the free edition of https://mobaxterm.mobatek.net/download.html; on Mac and Linux no need to install anything). No need to install Chapel -- we'll play with it on a cluster, and I will provide guest accounts.

## Time and Place

**Where:** Room 7010, Library Research Commons, SFU Burnaby Campus

**When:** Tuesday, October 23, 2018 at 3:00 PM

## Registration

Research Commons Page: https://www.lib.sfu.ca/about/branches-depts/rc/services/workshops/33770

Registration Page: https://www.lib.sfu.ca/node/33770/sfu_register

## Lesson

Workshop notes can be found at https://github.com/razoumov/publish/blob/master/08-seminarVersion.md.

**Comment by lfunderburk** [comment]
Hello @razoumov 
Do you have lesson materials you would like to add as part of the lesson?

**Comment by razoumov** [comment]
I added the workshop notes to the lesson.

**Comment by lfunderburk** [comment]
Thank you ^^
