### ISSUE TITLE
"Analyzing data using R" by Nafiseh Nafiseh Sedaghat

### ISSUE THREAD

**Issue by lfunderburk** [sciprog-sfu/sciprog-sfu.github.io#192]
## Description
In this workshop, we will talk about analyzing data using R. We will cover the following topics in this: 

1) Different types of data

 2) Cleaning data

 3) Exploring data using machine learning techniques.

Please be advised that we will go through simple and well-known methods of analyzing data such that attending this workshop can be helpful for every person from different majors whose have lots of data to analyze.

## Requirements

The basic requirements of attending this workshop is having a laptop with R and Rstudio. Specific packages include

library(mice)
library(caret)
library(RANN)
library(mlbench)
library(Biocomb)
library(factoextra)
library(outliers)

## Time and Place

**Where:** Room 7200, Library Research Commons, SFU Burnaby Campus

**When:** Tuesday, Nov 6, 2018 at 3:00 PM

## Registration

Research Commons Page:  https://www.lib.sfu.ca/about/branches-depts/rc/services/workshops/33791

Registration Page: https://www.lib.sfu.ca/node/33791/sfu_register

## Lesson

https://github.com/sciprog-sfu/sciprog-sfu.github.io/blob/master/lessons/2018-11-06_R/Intoduction%20to%20Data%20Analysis%20by%20%E2%80%9CNafiseh%20Sedaghat%E2%80%9D.pdf

**Comment by lfunderburk** [comment]
Hello @NaSed

We have booked the room from 3 to 4:30. Participants usually arrive about 5 minutes before to settle in. We can also ask people to setup in advance to make the most out of the booked time. If you are concerned about people not setting up prior to the workshop, one approach would be to set the first 15 minutes to ensure everyone is on the same page.

We are currently adding descriptions and submitting to Research Commons so that the SFU community is aware of your workshop. If possible, please submit:

A short description of what the workshop entails - one or two sentences summarizing your workshop is fine,
Prerequisites, i.e. a laptop with R (3.5.1) and Rstudio pre-installed along with packages: Bioconductor, Tidyverse, etc.
**before September 17** to add to the Research Commons description. You can add this information on the comments and I will add it in the description.

**Comment by NaSed** [comment]
@lfunderburk 
Hi Laura,

Sorry for my delay in responding. That is a brief description of my workshop:


In this workshop, I will talk about analyzing data using R. The topics that I would like to cover in this workshop are: 1) Different types of data, 2) Cleaning data, 3) Exploring data using machine learning techniques.

It is noteworthy that I will go through simple and well-known methods of analyzing data such that attending this workshop can be helpful for every person from different majors whose have lots of data to analyze.

The basic requirements of attending this workshop is having a laptop with R and Rstudio. I will let you know about the specific packages later maybe 2-3 weeks before the workshop.

Thanks for your kind help.

Best,
Nafiseh

**Comment by lfunderburk** [comment]
Thank you @NaSed 

I have updated your workshop description and will notify Research Commons of your workshop. 

Please let me know what your last name is, so that I can add it next to your workshop title. 

Let me know if there is further I can do to support you. 

Best,

Laura

**Comment by NaSed** [comment]
Hi Laura,

Thanks,
My last name is Sedaghat.

Best,
Nafiseh

**Comment by lfunderburk** [comment]
Hello Nafiseh, 

Thank you for letting me know. 

I have updated your name on the workshop description and have sent a message to Research Commons to add your workshop. 

I will send an email to the SciProg mailing list with a link to your workshop closer to the date. 

Let me know if there is anything I can do to support you. 

Best,

Laura

**Comment by NaSed** [comment]
> Hello Nafiseh,
> 
> Thank you for letting me know.
> 
> I have updated your name on the workshop description and have sent a message to Research Commons to add your workshop.
> 
> I will send an email to the SciProg mailing list with a link to your workshop closer to the date.
> 
> Let me know if there is anything I can do to support you.
> 
> Best,
> 
> Laura

Hi Laura,

Today is my workshop. I wanted to update the requirements and probably send a document to audience. Is it possible?

Thank you.

Best,
Nafiseh

**Comment by lfunderburk** [comment]
> > Hello Nafiseh,
> > Thank you for letting me know.
> > I have updated your name on the workshop description and have sent a message to Research Commons to add your workshop.
> > I will send an email to the SciProg mailing list with a link to your workshop closer to the date.
> > Let me know if there is anything I can do to support you.
> > Best,
> > Laura
> 
> Hi Laura,
> 
> Today is my workshop. I wanted to update the requirements and probably send a document to audience. Is it possible?
> 
> Thank you.
> 
> Best,
> Nafiseh

Hello Nafiseh, 

Thank you for following up. 

Please send updated requirements and document to lgutierr@sfu.ca - I can send an email to the sci prog emailing list. 

Laura
