### ISSUE TITLE
Heatmaps in R by Lisa N. Cao 

### ISSUE THREAD

**Issue by lfunderburk** [sciprog-sfu/sciprog-sfu.github.io#199]
## Description
In this workshop we will be going over how to generate Heatmaps, a type of visualization popular for describing high-dimensional datasets (such as genomic or spatial) through the use of colour grids. Participants will learn how to generate these maps using the heatmap() function in base R, and interactive heatmaps using the package heatmaply, which works on top of ggplot2. This workshop will be geared towards beginners.

Participants are encouraged to come in with a basic knowledge of R functions and syntax structure, as well as some basic graphical knowledge including hex colour codes. Because this workshop will be made to be as accessible as possible, I highly encourage tentative participants to come anyways. 

## Requirements
 At bare minimum, R and RStudio. The most recent versions are preferred but because heatmap() functions remain largely the same you can stick with what you have if need be. Heatmaply requires R versions above 3.0.0 and it's dependencies. 

Please run the following code ahead of time: 

> install.packages('heatmaply') 

Small datasets will be available for you to download during the workshop, but if you need one you can definitely use mtcars. Just run 

> install.packages('mtcars') 

## Time and Place

**Where:** Room 7010, Library Research Commons, SFU Burnaby Campus

**When:** Tuesday, January 29, 2019 at 3:00 PM

## Registration

https://www.lib.sfu.ca/about/branches-depts/rc/services/workshops/34117

## Lesson

https://github.com/lisancao/Heatmaps_in_R

**Comment by lisancao** [comment]
Hi Laura, 

My workshop should be for Jan 29, not Feb 12 :)

**Comment by lfunderburk** [comment]
Done :)

**Comment by lisancao** [comment]
Hi Everyone! All workshop materials can be found on my personal repository here :) 

https://github.com/lisancao/Heatmaps_in_R

**Comment by prosoitos** [comment]
Sorry I missed it today.

> install.packages('mtcars')

Little note: mtcars comes with R (part of base package `datasets`). So no need to install nor load it. The data is readily available.

**Comment by lisancao** [comment]
@prosoitos I had just realized that, updated materials should have it either hashed out or removed! Thanks :)
