### ISSUE TITLE
Screencasting workshops

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#23]
We got the question whether we should screencast workshops. At a meeting, we mentioned that we can use QuickTime on Macs. 

Alternatively, we could look into [Google Hangouts on Air](https://plus.google.com/hangouts/onair). We can use our newly created Gmail account for this. 
- It works on Windows and Macs (I don't know about Linux), since it's browser-based; all you need is to install the driver. 
- It's free. 
- We can broadcast live to people who can't attend in person, and even answer their questions remotely. 
- The video can automatically be uploaded to YouTube.

**Comment by katieannemills** [comment]
Could be great - don't forget to get [photo release forms](http://www.lib.sfu.ca/sites/default/files/11695/SpeakerRelease-Video-2013_rev1.pdf) for anyone you're going to record.

**Comment by BrunoGrandePhD** [comment]
Oh, I forgot to include an important detail: Google Hangouts has the ability to screencast and you can turn off the webcam video feed. So, we can avoid the issue of photo release forms.

**Comment by BrunoGrandePhD** [comment]
I just hope audio release forms aren't a thing...

**Comment by katieannemills** [comment]
yep, it's the same form.

**Comment by BrunoGrandePhD** [comment]
I meant that as a joke without even reading the form. Oh, well. That's good to know!

**Comment by katieannemills** [comment]
(sorry to be the no fun police here - I think this is an awesome idea, I just don't want you to have any nasty surprises down the line. SWC does photo releases, and it doesn't seem to cause any problems).

**Comment by BrunoGrandePhD** [comment]
Oh, it's not your fault. It's good that we know this before starting off in order to avoid surprises down the road, like you said. I just had a "Haha, that would be funny. Oh, wait... That's a thing." moment.

**Comment by BrunoGrandePhD** [comment]
I need to set up Google Hangouts for next session and print out some waiver forms.

**Comment by BrunoGrandePhD** [comment]
@BillMills, regarding the photo release form, should we create our own and replace SFU with "Scientific Programming Study Group at SFU"?

**Comment by katieannemills** [comment]
Hmmm, I can't offer legal advice to that depth; in the past, SWC workshops have used the local institution's waiver as is, I think; maybe shoot an email over to Ian Forsyth ([bottom](http://www.sfu.ca/avppolicy/contact_us.html)) - he'll at least know better than me.

**Comment by BrunoGrandePhD** [comment]
Email sent. We'll see what he says.
