### ISSUE TITLE
Question of renewing sciprog.ca domain

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#231]
It's the time of the year where I have to renew the sciprog.ca domain. It's about $20 per year. Sadly, I'm leaving SFU, so I figure I should either allow it to expire or transfer it to someone else. The GitHub URL (http://sciprog-sfu.github.io) will continue to work. 

What do people thing? Is the concise URL worth $20 per year? If so, is anyone willing to take on the domain?

**Comment by lisancao** [comment]
Although it's a nice-to-have I don't think we get the traffic to justify it. Most people come to the github anyways, and the *.github.io urls are very common now. 

As well, if we need a custom url down the road we can probably squeeze one out of the SFU domain.

**Comment by BrunoGrandePhD** [comment]
That's my thinking too.

**Comment by prosoitos** [comment]
I have also left SFU and I agree with that view anyway.

**Comment by BrunoGrandePhD** [comment]
Since no one has expressed the desire to keep the domain, I'm going to remove the CNAME file from the repository and migrate to using the github.io URL.
