### ISSUE TITLE
Keeping lessons and data together

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#25]
@ttimbers, I noticed that you created a [data directory](https://github.com/ttimbers/studyGroup/tree/gh-pages/data). I feel like it might be better to keep the lessons and data in one place, so that it's easier to find one from the other. For instance, I would create a directory for the lesson [here](https://github.com/ttimbers/studyGroup/tree/gh-pages/lessons) (_e.g._ `2015-07-14`) and store both the lesson markdown notes and data therein. What do you think?

**Comment by ttimbers** [comment]
Sure, go ahead and do that, please just update the link in the issue so
people can easily grab the data tomorrow.

**Comment by ttimbers** [comment]
When you move things, please make sure you link to the .zip file as I did
in the issues. This makes it easier for non Git/Github people to download
the data. Thanks.

**Comment by BrunoGrandePhD** [comment]
Done! Thanks.
