### ISSUE TITLE
Introduction to Perl by Kris Christensen

### ISSUE THREAD

**Issue by ttimbers** [sciprog-sfu/sciprog-sfu.github.io#26]
## Details

**Where:** Simon Fraser University, Burnaby Campus, SSB 7172
**When:** 11:30 am - 12:30 pm, Tuesday, September 28, 2015

**Etherpad:** https://etherpad.mozilla.org/2015-09-28-SFU
**Video Screencast:** http://www.youtube.com/watch?v=SrfkdwrMUzE

**Prerequisite knowledge:** Bash shell (basic)
**Dependencies:** Bash shell, Perl
### Windows
1. Install Git for Windows by downloading and running the installer (http://msysgit.github.io/). This will provide you with both Git and Bash in the Git Bash program. 
2. Install Perl. For Windows, you can look at the Strawberry Perl package (http://strawberryperl.com/). 
### Mac OS X

OS X comes by default with a Bash shell and Perl. We will be using the Terminal application (located under /Applications/Utilities). 
### Linux

The default shell is usually Bash, but if your machine is set up differently you can run it by opening a terminal and typing bash. There is no need to install anything. Also, Perl should be installed by default.

**Comment by kchriste2006** [comment]
Will probably need a text editor
Data link: https://raw.githubusercontent.com/kchriste2006/Perl_Lesson/master/Science_Progamming_KC_Alignments.txt and https://raw.githubusercontent.com/kchriste2006/Perl_Lesson/master/Science_Programming_Index.txt
Lesson Plan link: https://github.com/kchriste2006/Perl_Lesson/blob/master/Lesson_Plan_Science_Programming.md

**Comment by BrunoGrandePhD** [comment]
@kchriste2006, do you have a preference? Otherwise, I would recommend either Sublime Text or Atom, as they are both cross-platform and free. This would entail having users switch between their text editor and the terminal to run their scripts.

**Comment by stefanhannie** [comment]
Hi is there going to be a Google hangouts for remote participants? (I think I remember this happening last time.)

**Comment by ttimbers** [comment]
Yes, we will add the URL soon!

On Mon, Sep 28, 2015 at 11:14 AM, stefanhannie notifications@github.com
wrote:

> Hi is there going to be a Google hangouts for remote participants? (I
> think I remember this happening last time.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttimbers/studyGroup/issues/26#issuecomment-143831903.

## 

Tiffany A. Timbers, PhD
Banting Postdoctoral fellow, Leroux Lab
Department of Molecular Biology and Biochemistry
Simon Fraser University
8888 University Drive
Burnaby, BC, V5A 1S6

604-803-4962

tiffany.timbers@gmail.com
tiffanytimbers.com
@TiffanyTimbers

**Comment by BrunoGrandePhD** [comment]
@stefanhannie I added the link. Also, here it is: http://www.youtube.com/watch?v=SrfkdwrMUzE

**Comment by stefanhannie** [comment]
@brunogrande Awesome thanks. I'm watching.

**Comment by ttimbers** [comment]
@stefanhannie if you have any questions, throw them into the etherpad and we'll get Kris to answer them for you: https://etherpad.mozilla.org/2015-09-28-SFU
