### ISSUE TITLE
Python beginners : IS is not what it is ... sometimes

### ISSUE THREAD

**Issue by radaniba** [sciprog-sfu/sciprog-sfu.github.io#37]
# IS is not what it is

![](http://i.giphy.com/u1edH5vUfg8xO.gif)

The reason I had to write this, is that I found a lot of people, specially people starting using python, making this bad practice and pushing some code to production (and even papers)

This is a quick tip about the operator `is`, when to use it, and when to avoid it and what you should really consider when using it.

This is an issue that can affect your results, the effect can be small or big depending on the outcome of using the `is` operator.

In this small tutorial I will show you how `is` is not really what is
## Comparing Integers and Strings

In this section we will be comparing integers and string and test if they are equal to each others

``` python
x = 1
y = 1

print('x is y', bool(x is y))

('x is y', True)
```

That's great ! Now we will try to replicate this to another pair ov values for `x` and `y`

``` python
    x = 1000
    y = 1000

    print('x is y', bool(x is y))

    ('x is y', False)
```

As you can see, the comparison is returning `False` here ! Let's test with some float numbers instead of integers

``` python
    x = 0.005
    y = 0.005

    print('x is y', bool(x is y))

    ('x is y', False)
```

Strange ? What is this type of comparison was added in **a program that compares pvalues ? or selecting a type of action based on a threshold ?**

Ok let's keep going with Strings this time

``` python
    x = "I am Superman"
    y = "I am Ironman"

    print('x is y', bool(x is y))

    ('x is y', False)
```

This sounds correct

``` python
    x = "I am Superman"
    y = "I am Superman"

    print('x is y', bool(x is y))

    ('x is y', False)
```

Again this is returning False and this may be starting to make you think .. why on earth am using Python ?

No worries ! here is a simple explanation and a small trick on when to use (or not) the is operator
## Think of your variables as objects

When you declare two variable with the same value, either strings, integers or floats you actually are creating objects that are not related to each other.

```
a = "Hulk" --> Object1
b = "Hulk" --> Object2
```

When you compare `a is b` it is like you are asking if `Object1 is Object2`, which of course will be returning `False`

Now let's correct this a bit, I will be revisiting all the examples above but making sure I am using the same `Object` this time, and see how the result will be

``` python
    # Integers

    x = 1000
    #y = 1000
    y = x

    print('x is y', bool(x is y))

    # Floats

    x = 0.005
    #y = 0.005
    y = x

    print('x is y', bool(x is y))

    # Strings

    x = "I am Superman"
    #y = "I am Ironman"

    y = x

    print('x is y', bool(x is y))

    ('x is y', True)
    ('x is y', True)
    ('x is y', True)
```

Now that we are comparing same objects the results start to make more sense.

But can we still use different objects and still manage to get the right comparison ?

The answer is yes, instead of `is` use `==` , let's revisit the previous examples

``` python
    # Integers

    x = 1000
    y = 1000

    print('x is y', bool(x == y))

    # Floats

    x = 0.005
    y = 0.005

    print('x is y', bool(x == y))

    # Strings

    x = "I am Superman"
    y= "I am Superman"

    print('x is y', bool(x == y))

    ('x is y', True)
    ('x is y', True)
    ('x is y', True)
```

Ok : now we are comparing **values of objects** and returning the correct result.

That's it for today, I hope this will make you think that python is not as straightforward than it seems to be, in comparison to other languages that is correct, but you still need to pay attention to these small things that may affect deeply your results and your data description

![](http://i.giphy.com/nYioQ1xNGPFQs.gif)

**Comment by ttimbers** [comment]
Thanks for this tip @radaniba 

Can you explain why the first line  code example (repeated below) is true? 

```
x = 1
y = 1

print('x is y', bool(x is y))

('x is y', True)
```

**Comment by radaniba** [comment]
(am not sure) I think in python 2.x 1 and 0 are referring to Boolean True and False so : 

``` python

x = 1
y = 1

print('x is y', bool(x is y))

('x is y', True)

and

x = 0
y = 0

print('x is y', bool(x is y))

('x is y', True)
```

**Comment by ttimbers** [comment]
Thanks for clarifying!

**Comment by radaniba** [comment]
but more accurately here is the reason, should have done some research before :) 

> == is a value comparison, is is an object identity (memory location) comparison. You will often see that comparisons like x = 0 will give the intended result because small values are usually cached in Python, but you always want to be using == instead of is when checking equality because this behavior cannot be relied upon.

More .. I think the current implementation is setting the cache range from -5 to 256 

``` python

# upper range

x = 256
y = 256
print('x is y', bool(x is y))
('x is y', True)

x = 257
y = 257
print('x is y', bool(x is y))
('x is y', False)

#lower range

x = -5
y = -5
print('x is y', bool(x is y))
('x is y', True)

x = -6
y = -6
print('x is y', bool(x is y))
('x is y', False)

```

**Comment by katieannemills** [comment]
This is great stuff; would love to see these comments / questions combined into a lesson we can subrepo into the [collection](https://github.com/mozillascience/studyGroupLessons)!
