### ISSUE TITLE
Intro to Emacs & Multiple Cursors

### ISSUE THREAD

**Issue by dfornika** [sciprog-sfu/sciprog-sfu.github.io#41]
Is there interest in doing an intro to Emacs tutorial?

I'd suggest doing a brief general 'getting started' tutorial for those who aren't already familiar with emacs, then with the last ~15-20 minutes, I could demonstrate the use of [multiple cursors](https://github.com/magnars/multiple-cursors.el).  I use that feature a lot for editing 'batch' files before submitting them to a cluster, but there are lots of other creative uses for the feature.

**Comment by ttimbers** [comment]
@dfornika, that sounds great! It would be awesome if you could lead this session!

**Comment by dfornika** [comment]
Could someone label this as a workshop-idea please? I can't figure out how to do it.

**Comment by ttimbers** [comment]
Could you do this on Oct 19? That's the next session we need to fill.

**Comment by dfornika** [comment]
Yes, October 19th works for me.

**Comment by BrunoGrandePhD** [comment]
+1

**Comment by ttimbers** [comment]
@dfornika I made a workshop issue for this (https://github.com/ttimbers/studyGroup/issues/43), can you please fill in the info for prerequisite knowledge,  dependencies and environment setup for each OS?
