### ISSUE TITLE
Introduction to Emacs & Multiple Cursors by Dan Fornika

### ISSUE THREAD

**Issue by ttimbers** [sciprog-sfu/sciprog-sfu.github.io#43]
## Details

**Where:** Simon Fraser University, Burnaby Campus, SSB 7172
**When:** 11:30 am - 12:30 pm, Monday, October 26, 2015

**Prerequisite knowledge:** 
**Dependencies:** Emacs
**Etherpad:** https://etherpad.wikimedia.org/p/2015-10-26-SFU
## Official GNU Emacs site

https://www.gnu.org/software/emacs/
### Windows

There are two options available for installing Emacs on Windows:

Official GNU Emacs site for Windows:
http://ftp.gnu.org/gnu/windows/emacs/

Emacs Portable App for Windows:
https://github.com/mattfidler/EmacsPortable.App
### Mac OS X

http://emacsformacosx.com/
### Linux

emacs should be available via the system package manager, but if you'd prefer to download a source tarball they are available here:

http://ftp.gnu.org/gnu/emacs/
### Lesson Notes

https://github.com/dfornika/2015-10-26_emacs_tutorial/blob/master/emacs_and_multiple_cursors.md
##### Demo video on the Multiple Cursors package:

https://www.youtube.com/watch?v=jNa3axo40qM

**Comment by dfornika** [comment]
Is there a way that I can edit this directly in GitHub, or do I need to prepare a pull request of some sort?

**Comment by ttimbers** [comment]
I added you as a collaborator on the repo, so you should be able to do that now.
