### ISSUE TITLE
Introduction to LaTeX by Ross Churchley

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#47]
## Details

**Where:** Simon Fraser University, Burnaby Campus, SSB 7172
**When:** Monday, November 16, 2015 at 11:30 am - 12:30 pm

Etherpad: https://etherpad.wikimedia.org/p/2015-11-16-SFU

**Prerequisite knowledge:** 
**Dependencies:**

**Comment by rchurchley** [comment]
This workshop is a gentle and practical introduction to the LaTeX typesetting system. Even if you've never used LaTeX before, we'll have you typesetting beautiful documents in a little less than an hour. Topics will include:
- "Hello, world!"
- Sections, lists, and other commands
- Using packages
- Tables
- SFU's LaTeX thesis class.

Please note **the location has changed** and will now be held in the SFU Learning Commons on the 7th floor of the WAC Bennett Library (Burnaby campus).

You will need to install a LaTeX distribution before coming to the workshop --- give yourself some time to do this, as the installer is a couple gigs! Please see the [TeX Users Group website](https://latex-project.org/ftp.html) for instructions on how to set up a LaTeX distribution on your platform.

We will be using the cross-platform editor TeXWorks, which should be bundled with whatever distribution you install, but you may use any LaTeX editor you like (or even your favourite plain text editor!)

**Comment by lfunderburk** [comment]
Hi Ross,

I will miss this as I have class but I am certain your workshop will run smooth :). 

I'll tell Sebastian. He might be interested in going. 

Laura
