### ISSUE TITLE
Using Pandas for data analysis in Python by Tiffany Timbers

### ISSUE THREAD

**Issue by ttimbers** [sciprog-sfu/sciprog-sfu.github.io#54]
## Details

Pandas is an open source library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

**Where:** Simon Fraser University, Burnaby Campus, Library Research Commons
**When:** 11:30 am - 12:30 pm, Monday, November 30, 2015

**Prerequisite knowledge:** Entry level Python
**Dependencies:**  Python 3 (or higher) and Pandas library
</br>
**Etherpad:** https://etherpad.wikimedia.org/p/2015-11-30-SFU
**Notes:** https://github.com/PHY3009/pandas/blob/master/pandas.ipynb
**Data:** https://github.com/PHY3009/pandas/blob/master/data/behav_2.dat?raw=true
**Video:** https://plus.google.com/events/cf18eq2qn04toefaaqd9n6u38e0

**Comment by razoumov** [comment]
Would love to attend, but I'll be away that day teaching a visualization workshop in Winnipeg. Any chance we could move this to a later date in December?

**Comment by ttimbers** [comment]
Sorry, we already have this scheduled, and so will be holding it as scheduled. But, we can definitely do another variation of this lesson again in the near future. We will also be screen casting this session if you want to watch it remotely. The link should be available above in the issue shortly.
