### ISSUE TITLE
Add start and end time to events?

### ISSUE THREAD

**Issue by ttimbers** [sciprog-sfu/sciprog-sfu.github.io#72]
@brunogrande or @theavanrossum can you please add the start time to events? I want to include other events like the 1/2 day dib training workshops, and Res Baz, and I want to make it obvious on our webpage when these events are happening. I also think this is important for our regular events to get newcomers to start coming. Thanks!

**Comment by aliojjati** [comment]
Yes, I noticed there is a bunch of empty events on the webpage for Feb 
25 ...

On 2016-02-25 9:40 AM, Tiffany Timbers wrote:

> @brunogrande https://github.com/brunogrande or @theavanrossum 
> https://github.com/theavanrossum can you please add the start time 
> to events? I want to include other events like the 1/2 day dib 
> training workshops, and Res Baz, and I want to make it obvious on our 
> webpage when these events are happening. I also think this is 
> important for our regular events to get newcomers to start coming. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ttimbers/studyGroup/issues/72.

## 

Alireza

**Comment by ttimbers** [comment]
I just fixed that. Apparently you cannot have colons in the title of
events...

On Thu, Feb 25, 2016 at 9:43 AM, Alireza Hojjati notifications@github.com
wrote:

> Yes, I noticed there is a bunch of empty events on the webpage for Feb
> 25 ...
> 
> On 2016-02-25 9:40 AM, Tiffany Timbers wrote:
> 
> > @brunogrande https://github.com/brunogrande or @theavanrossum
> > https://github.com/theavanrossum can you please add the start time
> > to events? I want to include other events like the 1/2 day dib
> > training workshops, and Res Baz, and I want to make it obvious on our
> > webpage when these events are happening. I also think this is
> > important for our regular events to get newcomers to start coming.
> > Thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ttimbers/studyGroup/issues/72.
> 
> ## 
> 
> Alireza
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttimbers/studyGroup/issues/72#issuecomment-188898734.

## 

Tiffany A. Timbers, PhD
Banting Postdoctoral fellow, Leroux Lab
Department of Molecular Biology and Biochemistry
Simon Fraser University
8888 University Drive
Burnaby, BC, V5A 1S6

604-803-4962

tiffany.timbers@gmail.com
tiffanytimbers.com
@TiffanyTimbers
