### ISSUE TITLE
R (m)Apps with Shiny & Leaflet by Simon Goring

### ISSUE THREAD

**Issue by ttimbers** [sciprog-sfu/sciprog-sfu.github.io#74]
Learn how to create beautiful apps (that can run on the web!) with Shiny & Leaflet in R

**Where:** Simon Fraser University, Burnaby Campus, Library Research Commons
**When:** 11:30 am - 12:30 pm, Monday, April 11, 2016

**Prerequisite knowledge:** Entry level R
**Dependencies:**  R, shiny, leaflet, dplyr
</br>
**Etherpad:** https://etherpad.wikimedia.org/p/2016-04-11-SFU
**Notes:**  https://github.com/SimonGoring/ShinyLeaflet-tutorial
**Video:** 
# 

@simongoring from the University of Wisconsin has built a lesson to introduce shiny and leaflet, and has kindly offered to travel to SFU to teach us! The next few dates/times we have open are April 11, 25, May 9, 23. @simongoring, do any of those work for you? @theavanrossum, I know you are keen about this - are any of those dates no good for you?

**Comment by katieannemills** [comment]
do it! this lesson was awesome! :star2:

**Comment by SimonGoring** [comment]
Thanks @billmills!  I can't do either day in May, but April is open.

**Comment by SimonGoring** [comment]
Also thanks @ttimbers for the invite.

**Comment by ttimbers** [comment]
@SimonGoring we're happy to have you or any of the UBC R study group over to SFU anytime!

**Comment by theavanrossum** [comment]
Fantastic - thanks @SimonGoring! April 11th works for me

**Comment by ttimbers** [comment]
@SimonGoring @theavanrossum April 11th from 11:30-12:30 it is! I'll set up the event!

**Comment by ttimbers** [comment]
@SimonGoring just reminding you that you have been added to our schedule for the R (m)Apps with Shiny & Leaflet session in April 11th. I've added you as a collab to the repo, so please feel free to edit the first box in this issue with any info that the learners might need. Thanks again for doing this!

**Comment by SimonGoring** [comment]
Thanks @ttimbers, sorry for the delay in posting here, I'm really looking forward to meeting you all on the 11th.

The most recent draft of the tutorial is here:
https://github.com/SimonGoring/ShinyLeaflet-tutorial

The tutorial is designed as an Rmd file that people can compile directly to HTML themselves.  I've got some ideas for things I want to tweak, so stay tuned.

If there's anything in particular people are looking for, please let me know.

**Comment by ttimbers** [comment]
Thanks @SimonGoring, I'm really looking forward to this session!
