### ISSUE TITLE
Getting to know SciProg

### ISSUE THREAD

**Issue by lpix** [sciprog-sfu/sciprog-sfu.github.io#84]
Hi!
I just found out about your group, but I noticed that your group doesn't get the needed exposure to promote coding literacy at SFU.

Some ideas:
- Use Clubs Days to promote the group (I know it's a bit late for that). Maybe placing posters in the Sciences Buildings 
- Take it out of the Library. Have other events to encourage mingling among the members (181 is a lot of people!)
- Having workshops on the super-basics to advanced periodically.
- Using social media more often

I really look forward to meeting you guys (in person) though I don't have any projects at the moment. :(

**Comment by ttimbers** [comment]
Hi @lpix! Thanks for contacting us with your ideas. I've tagged the other organizers (@brunogrande, @theavanrossum, @razoumov & @vguerracanedo) to add them to the conversation you have started. 

If you're up for it, we'd love your help promoting the group. We're going to be discussing some of these issues at the co-working session on Monday at 11:30am in the Library Research Commons, it would be great if you could join us!

I am guessing you are at SFU? What department are you in?

Thanks again for starting this conversation!

**Comment by lpix** [comment]
Hi @ttimbers! 
I'd love to help out. However, I will be in Vancouver (today) and I don't know whether I will be there on time. 
I am a student at SFU, in Biology. My e-mail is lap3@sfu.ca, maybe we can chat through e-mail as I'm still getting used to GitHub :)

**Comment by lpix** [comment]
I think we can close this issue :)
