### ISSUE TITLE
Facebook group

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#92]
In a private email discussion with a new SciProg member, the idea of creating a Facebook group came up. I asked whether they thought it would be valuable for SciProg to have. Their response is quoted below. 

> I think that you could use Facebook to promote the group through Faculty Student Union's pages, but I also think that word-of-mouth is effective both online and offline. You could create a summer-special event and promote it through Facebook, as well as putting posters up around campus.

A Facebook group might nicely complement the reminder emails we send out. Some people might check their Facebook more diligently than they read their emails. Food for thought.

**Comment by lpix** [comment]
Hi everyone! 
I've been commenting around without introducing myself: I am the new SciProg member!
My name is Leslie, an undergrad in Biology, interested in Computational Biology, and looking forward to meeting you all and helping promote SciProg.

**Comment by lpix** [comment]
If you guys go along with this, we could live-stream the presentations/tutorials

**Comment by BrunoGrandePhD** [comment]
Alright, let's give this a try! I created a [Facebook group](https://www.facebook.com/groups/sciprog/) for SciProg. We should consider adding a prominent link (using a Facebook icon) on the website. We can discuss this at the Q&A session on June 20th. I'll try to bring my laptop to we can make changes to the website then and there.

**Comment by lpix** [comment]
Even though I had fun making my whimsical posts, I opted for a more conservative look that mirrors the style for the webpage. 
Images 1-5 are post templates, the rest are general announcements and the last two are facebook covers?
Also, I have attached a style guide with the fonts and sizes I used.
(sorry for the image sizes, markdown doesn't support changing image size[?!])
[Style Guide.pdf](https://github.com/sciprog-sfu/sciprog-sfu.github.io/files/368651/Style.Guide.pdf)

![1](https://cloud.githubusercontent.com/assets/16929101/16910225/5f3fd39a-4c8c-11e6-8b4b-734266899288.jpg)
![2](https://cloud.githubusercontent.com/assets/16929101/16910227/5f426c40-4c8c-11e6-9ac6-b2955ea7381d.jpg)
![3](https://cloud.githubusercontent.com/assets/16929101/16910224/5f3fb766-4c8c-11e6-9262-b2a3b81b2e3f.jpg)
![4](https://cloud.githubusercontent.com/assets/16929101/16910435/6fe95f26-4c8d-11e6-9ae2-2e2d169af04d.jpg)
![5](https://cloud.githubusercontent.com/assets/16929101/16910226/5f4019e0-4c8c-11e6-9950-cd7eb1783a8c.jpg)

> My attempt at minimalism
> ![6](https://cloud.githubusercontent.com/assets/16929101/16910239/70f5b6b8-4c8c-11e6-9b55-3e4cc19b118b.jpg)

![materials needed](https://cloud.githubusercontent.com/assets/16929101/16910240/70f7abee-4c8c-11e6-9a92-60598e9fbe9b.jpg)
![qna](https://cloud.githubusercontent.com/assets/16929101/16910241/70f941f2-4c8c-11e6-8331-39066fdbb6c3.jpg)
![sciprog ca](https://cloud.githubusercontent.com/assets/16929101/16910242/70fb3a0c-4c8c-11e6-8245-ece12d4049a9.jpg)
![sciprog](https://cloud.githubusercontent.com/assets/16929101/16910243/70fe0200-4c8c-11e6-9827-fd72b8cefbb1.jpg)

**Comment by BrunoGrandePhD** [comment]
@lpix: I added a Facebook icon to the website: http://sciprog.ca/

**Comment by BrunoGrandePhD** [comment]
Unfortunately, nobody maintains the Facebook group, so I'll archive it.
