### ISSUE TITLE
Promote SciProg to undergraduate students in relevant 400-level courses

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#95]
During the Q&A session on June 6th, @vguerracanedo, @theavanrossum, @lpix and I discussed the possibility of promoting SciProg to undergraduate students. Specifically, we think that there are some who are enthusiastic to learn more about scientific computing, but they don't know how to learn more. SciProg would be perfect for them, but we need to get the word out. 

One way would be to send a slide about SciProg to professors teaching relevant courses (_e.g._ Comparative Genomics) to share with their students. Currently, the most common departments with 10+ SciProg members are the following in decreasing order. We can focus on the top three departments for now and expand to the others over time. 
1. Biological Sciences
2. Computing Sciences
3. Molecular Biology and Biochemistry
4. Statistics and Actuarial Science
5. Mathematics
6. Physics
7. Engineering Science
8. Chemistry

**Comment by lpix** [comment]
I will screen out courses relevant to the group and I will get back to you shortly!

**Comment by lpix** [comment]
Here is the list of Undergrad (UG) classes offered this summer. 
NOTE 1: I chose classes someone like myself would be interested in (ie Biology-oriented, maybe in the future we can include other areas)
NOTE 2: I added the topics to get workshop/speaker ideas (I am thinking Forensic Genomics!!)
NOTE 3: I'll try to make a more comprehensive list, something we can just check off for availability each semester. That's going to take time though...
NOTE 4: I included some lower level courses as well to target the beginners

[UG Classes offered Summer 2016.pdf](https://github.com/sciprog-sfu/sciprog-sfu.github.io/files/310217/UG.Classes.offered.Summer.2016.pdf)

**Comment by vguerracanedo** [comment]
Wow, that's a nice list. Thank you for putting that together guys.

Should we plan to send one major email out to everyone at the beginning of
the semester, and then one email to the departments at the beginning of
each month? If nobody is thinking about doing this, I could send the emails
out.

V

On Sat, Jun 11, 2016 at 4:44 AM, Leslie notifications@github.com wrote:

> Here is the list of Undergrad (UG) classes offered this summer.
> NOTE 1: I chose classes someone like myself would be interested in (ie
> Biology-oriented, maybe in the future we can include other areas)
> NOTE 2: I added the topics to get workshop/speaker ideas (I am thinking
> Forensic Genomics!!)
> NOTE 3: I'll try to make a more comprehensive list, something we can just
> check off for availability each semester. That's going to take time
> though...
> UG Classes offered Summer 2016.pdf
> https://github.com/sciprog-sfu/sciprog-sfu.github.io/files/310217/UG.Classes.offered.Summer.2016.pdf
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/95#issuecomment-225355491,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALX_Du-Q_bb8lPQCR3j-3bbCp-J5h6jSks5qKp-dgaJpZM4IvTwn
> .

## 

Vanessa Guerra Canedo, M.Sc.

Ph.D. student, Hart Lab
Department of Biological Sciences
Simon Fraser University, 8888 University Drive, Burnaby, BC, V5A 1S6
