### ISSUE TITLE
Organize Summer 2016 Workshops

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#96]
~~We still have plenty of open slots for one-hour workshops this summer (denoted by "____"). Choose a date that fits your schedule. We don't mind moving Q&A sessions around to be accommodating.~~

**We have filled up every slot for the summer!** If you still want to lead a lesson, [open a new issue](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/new) telling us what you want to teach and we'll schedule you for fall. Thanks, everyone!

**Time:** Mondays at 10:30 am
**Duration:** One hour, but can be up to two hours
**Location:** Research Commons, W.A.C. Bennett Library 7th floor, SFU Burnaby
## Schedule

May 2nd – Co-working session
May 11th – [DIB Training Rmarkdown half-day workshop](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/70)
May 16th – Co-working session
~~May 23rd – Victoria Day Holiday~~
May 30th – [Remote Computer Access: Submitting jobs to Westgrid's clusters](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/91) / @vguerracanedo 
June 6th – [Q&A Session](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/79)
June 13th – [Data manipulation in R with dplyr](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/94) / @theavanrossum 
June 20th – [Q&A Session](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/111)
June 27th – [Scientific Toolkit in Python (scipy and numpy)](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/99) / @MaralDehghani 
July 4th – [Crafting publication-worthy figures using ggplot2 and cowplot](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/104) / @lpix 
July 11th – [The Basics of Wordpress](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/100) / @Marindeout 
July 18th – [Q&A Session](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/116)
July 25th – [Data analysis in Python using pandas](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/112) / @kenjsc
~~August 1st – BC Day Holiday~~
August 8th – [Parallel Computing](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/103) / @razoumov 
August 15th – [Introduction to Shiny for Interactive Data Visualization](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/101) / @daattali 
August 22nd – [Machine Learning and Random Forest](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/107) / @Hypogeous 
August 29th – [Introduction to Bash](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/97) / @vguerracanedo 
## Grab Bag for Workshop Topics

We asked SciProg members what they wanted to learn this summer and this is a summary of their responses. So, if you're looking for inspiration on what to teach, look at the unchecked boxes below and comment with which one you would like to teach. 
- [ ] Advanced functions in R
- [x] Bash
- [ ] C++
- [ ] Circos
- [x] Data analysis in Python / pandas / matplotlib / seaborn
- [ ] Databases / SQL
- [x] dpylr / Data wrangling in R
- [ ] Efficient simulations (in R or another language)
- [ ] Generalized linear models (GLMs)
- [x] Git
- [x] Going through the process of a data analysis project: Raw data -> R project -> Version control -> Rmarkdown -> Analysis -> Etc.
- [x] Graphing in R / Publication-worthy plots / cowplot?
- [x] LaTeX
- [x] Machine learning techniques
- [ ] Mixed effects models
- [ ] Object-oriented programming
- [x] Parallel computing
- [x] Rmarkdown
- [ ] ROOT
- [x] Scientific toolkit in Python (scipy and numpy)
- [x] Shiny / Interactive plotting in R
- [ ] SQLAlchemy 
- [ ] Various R packages

**Comment by vguerracanedo** [comment]
August 29th - Intro to Bash / @vguerracanedo

**Comment by BrunoGrandePhD** [comment]
@vguerracanedo, I created a new issue for your workshop. Feel free to edit it!

https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/97

**Comment by MaralDehghani** [comment]
June 20th, June 27th, July 4th and July 11th, all work for me.
I can run sessions on "Latex" and "Scientific toolkit in Python (scipy and numpy)".

**Comment by BrunoGrandePhD** [comment]
@MaralDehghani, I'll slot you in on June 20th, as it's the earliest open slot we have. Which topic do you prefer teaching first? Maybe the one you would need the least amount of time to prepare for. I'll schedule the other topic for later in the summer to give you a break. Thanks!

**Comment by Marindeout** [comment]
I would like to give a workshop about 'the basics of Wordpress' on July the 11th if possible.

**Comment by MaralDehghani** [comment]
I go for  Scientific toolkit in Python (scipy and numpy) on June 20th.

**Comment by BrunoGrandePhD** [comment]
@MaralDehghani, I just realized that June 20th is a tentative Q&A session. I will give you a bit more time and schedule you on June 27th instead, if you don't mind. I want to fill in the slots between co-working sessions first.

**Comment by BrunoGrandePhD** [comment]
@billmills, is there any chance we can summon you to SFU to lead a session this summer?

**Comment by daattali** [comment]
I can do Shiny on July 11 or 18.

Full disclaimer: I'm waiting for an appointment in Toronto sometime this summer and when I get in I'll have to fly out within a couple days, so there's a small chance I'll cancel last minute.

**Comment by NickDulvy** [comment]
Guys, Can you drop me off this instagram-like feed?

Nick

----- Original Message -----

**Comment by MaralDehghani** [comment]
Bruno, I am absolutely fine with that.

**Comment by BrunoGrandePhD** [comment]
Sorry about that, @nickdulvy. Unfortunately, we have no control over who gets notifications. Your best bet is to change the notification setting for the repository from "Watching" to "Not Watching" (see top right of [repo page](https://github.com/sciprog-sfu/sciprog-sfu.github.io)). This way, you'll only get notified when mentioned. I hope this helps!

**Comment by BrunoGrandePhD** [comment]
@daattali, I'll slot you in on July 18th. And if you leave for Toronto before then, it's totally fine. Thanks for letting us know.

**Comment by razoumov** [comment]
I can teach parallel computing. Any date after mid-July (I'll be mostly away until then) is Ok -- feel free to put me into the schedule. Also, I don't see any topics related to 3D visualization -- how come? I can teach  any of the topics in ParaView or VisIt visualization.

**Comment by BrunoGrandePhD** [comment]
@razoumov, the topic grab bag was compiled from the suggestions given in the recent summer survey. No one mentioned 3D visualization, but I think that would still be useful and I would like to leverage your expertise on the topic. I'll schedule a workshop on parallel computing for August 8th, since there is current demand from SciProg members. 

Given that you are already planning on giving a workshop on C/C++ optimization in fall, would you prefer to teach the 3D visualization this summer or in fall. I leave it up to you.

**Comment by BrunoGrandePhD** [comment]
@ttimbers, I see you're [teaching](https://github.com/minisciencegirl/studyGroup/issues/121) about `lm` and `glm` at the UBC study group on July 8th. We've gotten interest from the SciProg members to teach exactly this. Would it be possible for you to re-give your lesson at SFU on July 25th? I understand if your new position keeps you too busy for the trek to SFU.

**Comment by razoumov** [comment]
@brunogrande Aug-08 for parallel computing sounds great. Yes, I'll give a separate session on C/C++ optimization in the fall. Let's leave 3D visualization for any of the unfilled spots, either this summer or during the academic year -- just confirm the date with me when you put it into the calendar. Thanks.

**Comment by ttimbers** [comment]
I'll be on vacation then, but could do another date later in the summer, but before September (if you are still sticking to Mondays). I'm back from vacation on Aug 10th.

**Comment by BrunoGrandePhD** [comment]
@razoumov, since we have been successful with filling out workshop slots for the summer, we'll keep the workshop on 3D visualization for the academic year. 

@ttimbers, would August 22nd work for you?

**Comment by Hypogeous** [comment]
I can do machine learning/random forest on Aug 22nd. Jason

**Comment by ttimbers** [comment]
If @Hypogeous is going to do machine learning/random forest on Aug 22nd then I'll bow out.

**Comment by BrunoGrandePhD** [comment]
@Hypogeous, that's great! I slotted you in on August 22nd. 

@ttimbers, that's fine. Perhaps someone else (@aliojjati?) can teach your lesson once you've written up your notes.

**Comment by ttimbers** [comment]
absolutely! I mean I'd love to come, but my schedule just wont let it happen :(

**Comment by MaralDehghani** [comment]
How come the Latex session on August 15th was assigned to me?! I never said I am available on that day!!

**Comment by BrunoGrandePhD** [comment]
@MaralDehghani, that's my mistake. I was creating several workshops at once and I must have gotten some mixed up. 

I would rather not schedule you to lead two workshops within a week of one another (June 20th and 27th). How about we keep the LaTeX workshop for fall? If you're keen on teaching it this summer, then let me know and perhaps we can arrange something.

**Comment by MaralDehghani** [comment]
Sure. Let us hold a session on Latex in Fall.
