### ISSUE TITLE
"Scientific Toolkit in Python (scipy and numpy)" by Maral Dehghani

### ISSUE THREAD

**Issue by BrunoGrandePhD** [sciprog-sfu/sciprog-sfu.github.io#99]
## Description

This workshop aims to introduce participants to the packages Scipy and Numpy for Scientific Computing. A quick introduction to python will be given at the beginning of the workshop. 

The following topics will be covered depending on how well it goes:

```
1. Introduction to Python
    a. Numerical types
    b. Containers
    c. Control flow
2. NumPy
    a. Arrays
    b. Matrices
    c. Basic operations on Arrays and Matrices
    d. Operation along axes
    e. Slicing arrays
    f. Reshaping
    g. NumPy for Linear Algebra
3. Matplotlib
    a. Scatter Plot
    b. Histogram
    c. Box Plot
4. SciPy
    a. SciPy for Optimization
    b. SciPy for Statistics
    c. SciPy for Linear Algebra
```
## Time and Place

**Where:** Simon Fraser University, Burnaby Campus, Library Research Commons
**When:** Monday, June 27th, 10:30-11:30 am
## Required Preparation

**Software Dependencies** 

See the [attached installation instructions](https://github.com/sciprog-sfu/sciprog-sfu.github.io/files/332391/Python_NumPySciPy.pdf). 
## Links

**Etherpad:** https://etherpad.wikimedia.org/p/SFU_Python_2016_June
**Lessons Notes:**
https://github.com/sciprog-sfu/sciprog-sfu.github.io/files/341548/Python_SciProg.pdf

**Registration:** http://www.lib.sfu.ca/about/branches-depts/rc/30611

**Comment by BrunoGrandePhD** [comment]
@MaralDehghani, when you get a chance, comment with the details relating to your workshop so I can update the "TBA" values.

**Comment by BrunoGrandePhD** [comment]
@MaralDehghani, since your workshop is next week, can you comment with details on your lesson so I can update the "TBA" values? Specifically, I need a description, required software dependencies and assumed knowledge.

**Comment by MaralDehghani** [comment]
Hi There,

Sure. I will send you some details on my course by Wednesday.
M.

----- Original Message -----

**Comment by vguerracanedo** [comment]
Hi @MaralDehghani, 
I don't mean to be a drag, but I was wondering if you had the outline for the upcoming workshop. I was hoping to send the email out to the sciprog group in the following 24 hours about your workshop. We will also try to get the info to the library so they can advertise it. 
Best, 
V

**Comment by MaralDehghani** [comment]
Hi Vanessa,

Thanks for your email and sorry about the delay.
I am sending it to you today.
I apologize for the delay.

Regards,
Maral

----- Original Message -----

**Comment by MaralDehghani** [comment]
Hello All, 

I have attached the installation guide for the ones who do not intend to use IPython, as well as the outline of the course. 
I also put it in the following Etherpad, which I am going to use on Monday: 
https://etherpad.wikimedia.org/p/SFU_Python_2016_June 

Here is the outline: 
1. Introduction to Python 
a. Numerical types 
b. Containers 
c. Control flow 
2. NumPy 
a. Arrays 
b. Matrices 
c. Basic operations on Arrays and Matrices 
d. Operation along axes 
e. Slicing arrays 
f. Reshaping 
g. NumPy for Linear Algebra 
3. Matplotlib 
a. Scatter Plot 
b. Histogram 
c. Box Plot 
4. SciPy 
a. SciPy for Optimization 
b. SciPy for Statistics 
c. SciPy for Linear Algebra 

I may skip some of the subjects depending on the level of the class, number of attendees, their interest and background. 
I know there are so many sub-topics, I will modify it based on the class. 

Regards, 
Maral 

----- Original Message -----
